### ISSUE TITLE
My Requests: Filter(Created By)filter does not display

### ISSUE THREAD

**Issue by Heyam-Alsaidi** [MasterteamSA/Pplus-Simah-Web#1]
Steps To Reproduce:
1- Login (htaha\h@123456) http://94.127.212.105:2000/#portfolios
2- Click on the arrow from the Username tab 
3- Choose My Requests

Actual result:
(Created By)filter does not display
![image](https://user-images.githubusercontent.com/99599878/175936765-98981835-0b28-445f-960e-6417f78997ab.png)

Expected result:
![image](https://user-images.githubusercontent.com/99599878/175937026-6b9c37bc-ac91-43ff-a645-298de7881afc.png)

**Comment by JarrarMo** [comment]
@Heyam-Alsaidi we agreed with @fdahamshehh to remove it, since the created column will always be the same user.

**Comment by Heyam-Alsaidi** [comment]
@WalaaAhElsayed PLease confirm

**Comment by Heyam-Alsaidi** [comment]
Passed 
![image](https://user-images.githubusercontent.com/99599878/176175288-2f896d25-c92e-4168-8120-0e5ec2da77c6.png)
