### ISSUE TITLE
PDP: The portfolio project field is incorrectly reflected on the project workspace

### ISSUE THREAD

**Issue by Heyam-Alsaidi** [MasterteamSA/Pplus-Simah-Web#10]
Steps To Reproduce:
1- Login (halsaidi\Master@123)
http://94.127.212.105:2000/#portfolios
2- URL Project link
http://94.127.212.105:2000/#project/7aa24218-b0ef-ec11-b838-001dd8b71ff7

Actual result:
 The portfolio project field is incorrectly reflected on the project workspace
![image](https://user-images.githubusercontent.com/99599878/176164000-d09a42a8-8573-4d80-8e50-135d66f3fbce.png)

Expected result:
should be all project fields are correctly reflected on the project workspace
![image](https://user-images.githubusercontent.com/99599878/176163942-b9a2fa7e-48c7-48b0-b8f5-f77e1a9c2c4e.png)

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/176178632-d5ce77b1-ef32-4d63-a201-9f2323dcb4ef.png)

**Comment by Heyam-Alsaidi** [comment]
Passed 
![image](https://user-images.githubusercontent.com/99599878/176179178-c45be33b-e8dd-4846-a2cd-386e3f6ea32f.png)
