### ISSUE TITLE
My Tasks: the task list sorted does not from oldest to latest 

### ISSUE THREAD

**Issue by Heyam-Alsaidi** [MasterteamSA/Pplus-Simah-Web#11]
Steps To Reproduce:
1- Login (halsaidi\Master@123)
http://94.127.212.105:2000/#portfolios
2- URL Project link
http://94.127.212.105:2000/#project/15173646-50c6-4a38-a4db-14368f260470
3- Click on MY Tasks

Actual result:
the task list is sorted does not from oldest to latest 
![image](https://user-images.githubusercontent.com/99599878/176167971-49134c36-0321-4f26-a516-9bd52a393925.png)

Expected result:
the task list should be sorted from oldest to latest 
![image](https://user-images.githubusercontent.com/99599878/176170681-993b9eef-bbe3-4170-83be-3d02f32dd76d.png)

**Comment by JarrarMo** [comment]
![image](https://user-images.githubusercontent.com/53216161/176181861-c73a70e5-57f9-40dd-be60-33d419594ef5.png)

**Comment by Heyam-Alsaidi** [comment]
Passed 
![image](https://user-images.githubusercontent.com/99599878/176186288-17e6bded-6869-4d57-9125-f71c94bc18af.png)
