### ISSUE TITLE
My Tasks: the task list is sorted does not from oldest to latest 

### ISSUE THREAD

**Issue by Heyam-Alsaidi** [MasterteamSA/Pplus-Simah-Web#12]
Steps To Reproduce:
1- Login (halsaidi\Master@123)
http://94.127.212.105:2000/#portfolios
2- URL Project link
http://94.127.212.105:2000/#project/7aa24218-b0ef-ec11-b838-001dd8b71ff7
3- Click on My Tasks

Actual result:
the task list is sorted does not from oldest to latest 
![image](https://user-images.githubusercontent.com/99599878/176167971-49134c36-0321-4f26-a516-9bd52a393925.png)

Expected result:
the task list should be sorted from oldest to latest 
![image](https://user-images.githubusercontent.com/99599878/176170681-993b9eef-bbe3-4170-83be-3d02f32dd76d.png)

**Comment by saqratieh** [comment]
Two versions have been created by mistake 

Closing and removing phase 1 label so it will not be counted in the QA report
