### ISSUE TITLE
Stakeholder page : The “Influence” and “Interest” will be mandatory fields

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Pplus-Simah-Web#18]
![image](https://user-images.githubusercontent.com/86906875/200498451-950cb54d-7cf8-4861-ae2b-b761c1d11957.png)
![image](https://user-images.githubusercontent.com/86906875/200498610-3837aa14-113e-422f-bf09-479615d0826f.png)

**Comment by ealtiti** [comment]
![image](https://user-images.githubusercontent.com/85454412/200522299-c0f89f4e-1ba1-4757-9e29-3d0ddaef5b04.png)

**Comment by rhamad4** [comment]
fixed
