### ISSUE TITLE
Formatting error, should be (dd-mm-yyyy) instead of (mm/dd/yyyy)

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Pplus-Simah-Web#2]
Steps To Reproduce:
1- Login (htaha\h@123456) http://94.127.212.105:2000/#portfolios
2- Click the arrow on the Username tab
3- Choose My Requests

Actual result:
Date not displayed as (format dd-mm-yyyy)
![image](https://user-images.githubusercontent.com/107788214/175961481-7237cc4d-693c-40db-b271-bc3f149c9dbe.png)

Expected result:
![image](https://user-images.githubusercontent.com/107788214/175960751-daaa8a1b-22d6-4c6a-8887-2f78ca5bbe7c.png)

**Comment by WalaaAhElsayed** [comment]
Please close this ticket, we used this format in the whole system and we need to save the consistency
