### ISSUE TITLE
Stakeholders page : system does not display the added new "Suggested Strategy" 

### ISSUE THREAD

**Issue by rhamad4** [MasterteamSA/Pplus-Simah-Web#24]
![image](https://user-images.githubusercontent.com/86906875/200538923-f011b81c-ccc0-4465-acbb-b9f9fac1589d.png)

http://94.127.212.105:2000/#project/39618c3b-070c-ed11-b815-001dd8b723e0

**Comment by JarrarMo** [comment]
@ealtiti  Lets check the mapping

**Comment by rhamad4** [comment]
fixed
