### ISSUE TITLE
 My Requests: The fields name are incorrect not matched with BRD

### ISSUE THREAD

**Issue by Heyam-Alsaidi** [MasterteamSA/Pplus-Simah-Web#3]
Steps To Reproduce:
1- Login (halsaidi\Master@123) http://94.127.212.105:2000/#portfolios
2- Click on the arrow from the Username tab
3- Choose My Requests

Actual result:
1-The fields name are incorrect
![image](https://user-images.githubusercontent.com/99599878/175961692-020013de-fc66-4d88-ba34-84b80f646b30.png)

Expected result:
1-
![image](https://user-images.githubusercontent.com/99599878/175961902-1fe47d02-de56-4954-9af8-39db8c836bc3.png)

**Comment by WalaaAhElsayed** [comment]
Please this ticket, as we agreed with Olayn to not do it
