### ISSUE TITLE
Lesson Learned: When the user searches by category, the first project of the selected category type is not expanded by default

### ISSUE THREAD

**Issue by hebaabutaha** [MasterteamSA/Pplus-Simah-Web#6]
Steps To Reproduce:
1- Login (htaha\h@123456) http://94.127.212.105:2000/#portfolios
2- Click the arrow on the Username tab
3- Choose Lesson Learned

Actual result:
When the user searches by category, the first project of the selected category type is not expanded by default.
Only the first project is expanded when the category type (risk) is selected.

![image](https://user-images.githubusercontent.com/107788214/176114637-0a9e2d00-b3ba-4c29-b67d-250b8ee89de6.png)
![image](https://user-images.githubusercontent.com/107788214/176114939-b7652379-916e-4034-9a35-21c0342bda19.png)

Expected result:
When the user search by category the first project from the selected category type will be expanded by default
![image](https://user-images.githubusercontent.com/107788214/176118444-503b2ae1-91a3-4c26-9d47-0a0ad491493d.png)

**Comment by aolayyan** [comment]
duplicated with 
https://github.com/MasterteamSA/Pplus-Simah-Web/issues/7

**Comment by hebaabutaha** [comment]
#6 the first project of the selected category type is not expanded by default
#7 When the user searches by category, do not hide projects that do not belong to the selected category type.
So #6 is not a duplicate of #7
 @aolayyan

**Comment by Heyam-Alsaidi** [comment]
Passed
![image](https://user-images.githubusercontent.com/99599878/176370748-fec0e36a-3add-4035-8304-761e6affa72a.png)
