### ISSUE TITLE
Project Schedule: Does not display the Deliverables task because its the same level as Task Summary

### ISSUE THREAD

**Issue by Heyam-Alsaidi** [MasterteamSA/Pplus-Simah-Web#8]
Steps To Reproduce:
1- Login (halsaidi\Master@123)
http://94.127.212.105:2000/#portfolios
2- URL Project link
http://94.127.212.105:2000/#project/15173646-50c6-4a38-a4db-14368f260470
3- Click on the project schedule tab

Actual result:
Does not display the Deliverables task because its the same level as Task Summary
![image](https://user-images.githubusercontent.com/99599878/176138755-12ed042f-e4dc-40fa-a32c-acca4b0848ad.png)
Expected result:
Should be displayed all tasks l level 
![image](https://user-images.githubusercontent.com/99599878/176140146-62fc4a1d-ff9c-4592-b804-7df9f6c46e33.png)
IN Design
![image](https://user-images.githubusercontent.com/99599878/176141138-dda6aefe-d6d1-4ee0-b7be-46e22a264b0f.png)

**Comment by JarrarMo** [comment]
@Heyam-Alsaidi I believe this structure is invalid, I will check with @WalaaAhElsayed
